### ISSUE TITLE
Assignment on Git at MFR17

### ISSUE THREAD

**Issue by pattacini** [easy-peasy-robotics/easy-peasy-robotics.github.io#13]
Hello @easy-peasy-robotics/mfr17-participants 

Now that you're in the team, what about warming up in sight of the crash course?
Then, let's go through the very basics of `git` by taking this simple assignment 📝 👨‍🎓 

- Click on the link https://classroom.github.com/a/TdwXeyIF and accept the assignment
- You'll be given a private repository along with a guide on how to complete the assignment using the so-called **smoke test**.

Enjoy!

---

Did you receive this notification from GitHub, right? 😉 
In case not, check out instructions on [**how to trim** GitHub notifications](https://github.com/easy-peasy-robotics/easy-peasy-robotics.github.io/wiki/Before-arriving-at-the-venue#aob) 🔔

**Comment by pattacini** [comment]
Congrats to @graitanto21 for scoring the first point 🎖 

Check out the [gradebook](https://easy-peasy-robotics.github.io/mfr17-gradebook).

**Comment by pattacini** [comment]
Good job @NovelloDavide 👍

**Comment by pattacini** [comment]
@robertorovella91 and @joseph280 made the grade as well 🎉

**Comment by traversaro** [comment]
@RafGiammario can you proceed with the preliminary assignement? Thanks!
