### ISSUE TITLE
CMakefile build generates an error 

### ISSUE THREAD

**Issue by dinies** [easy-peasy-robotics/easy-peasy-robotics.github.io#3]
When I try to execute the **test.sh** in  __/tutorial_cartesian-interface/smoke-test/__ it returns the following output
```cmake
CMake Error at CMakeLists.txt:29 (add_library):
  Target "TestTutorialCartesianInterface" links to target "YARP::YARP_rtf"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?
```
I have followed every step of the guide https://github.com/vvv-school/vvv17/wiki/How-to-prepare-your-system on Ubuntu 16.04LTS with a kinetic ROS distro and then I followed the final steps for the *smoke-test* execution found in https://github.com/easy-peasy-robotics/easy-peasy-robotics.github.io/wiki/Before-arriving-at-Campus-Party

Any help would be appreciated, thank you !

**Comment by pattacini** [comment]
@dinies what is the output of:
```sh
$ env | grep -i rtf
```

**Comment by pattacini** [comment]
@dinies any news?

**Comment by pattacini** [comment]
We agreed to continue with the VM in the end.
