### ISSUE TITLE
[Question] how many days will last WEB20?

### ISSUE THREAD

**Issue by MartinaRuocco** [easy-peasy-robotics/easy-peasy-robotics.github.io#30]
Hi, 

I am a bit confused, will the course last 2 days as stated in the README of 4 days as stated [here](https://easy-peasy-robotics.github.io/editions/web20/open-call.html)?

**Comment by pattacini** [comment]
Hi @MartinaRuocco 

The official open call that you linked above says 4 days, which is the duration of the WEB20 edition.

You may have landed on the EPR homepage that instead reports 2 days for courses we held in the past and that ran in person.

**Comment by MartinaRuocco** [comment]
Perfect thank you!
