### ISSUE TITLE
Control Challenges

### ISSUE THREAD

**Issue by pattacini** [easy-peasy-robotics/easy-peasy-robotics.github.io#32]
I'm sure that you can do better than 

https://janismac.github.io/ControlChallenges/?eyJjb2RlIjoiZnVuY3Rpb24gY29udHJvbEZ1bmN0aW9uKGJsb2NrKVxue1xuICByZXR1cm4gMyooMC1ibG9jay54KTtcbn1cblxuXG4iLCJsdmxfaWQiOiJUdXRvcmlhbEJsb2NrV2l0aEZyaWN0aW9uIn0=

**Comment by Nesheit** [comment]
function controlFunction(block)
{
  return 4.5*(0 - block.x) + 4.5*(0 - block.x)*block.T - 4.5*block.dx;
}

It's 2.32 seconds

**Comment by abdelhakim96** [comment]
Challenge 1 solution: https://janismac.github.io/ControlChallenges/?eyJjb2RlIjoiZnVuY3Rpb24gY29udHJvbEZ1bmN0aW9uKGJsb2NrKVxue1xuICBcbiAgcmV0dXJuIC0xMCpibG9jay5keC03MCpibG9jay54O1xufVxuXG5cbiIsImx2bF9pZCI6IlR1dG9yaWFsQmxvY2tXaXRoRnJpY3Rpb24ifQ==

**Comment by claudioverardo** [comment]
http://janismac.github.io/ControlChallenges/?eyJjb2RlIjoiZnVuY3Rpb24gY29udHJvbEZ1bmN0aW9uKGJsb2NrKVxue1xuICByZXR1cm4gLTIyKmJsb2NrLnggLSA3KmJsb2NrLmR4XG59XG5cbiIsImx2bF9pZCI6IlR1dG9yaWFsQmxvY2tXaXRoRnJpY3Rpb24ifQ==

1.3 seconds

**Comment by mett96** [comment]
Tutorial 1: 0.62 s

https://janismac.github.io/ControlChallenges/?eyJjb2RlIjoiZnVuY3Rpb24gY29udHJvbEZ1bmN0aW9uKGJsb2NrKVxue1xuICB2YXIga3AgPSAxNTA7XG4gIHZhciBrZCA9IDIwO1xuICAvLyAwLjYyXG4gIFxuICBrcCA9IDE1MDtcbiAga2QgPSAyMDtcbiAgXG4gIHJldHVybiBrcCooMC1ibG9jay54KS1rZCpibG9jay5keDtcbn1cblxuXG4iLCJsdmxfaWQiOiJUdXRvcmlhbEJsb2NrV2l0aEZyaWN0aW9uIn0=

**Comment by Nesheit** [comment]
function controlFunction(block)
{
  return 900*(0 - block.x) + 45*(0 - block.x)*block.T - 90*block.dx;
}

Now it's 0.48 sec.

**Comment by mett96** [comment]
Tutorial 2: 0.4 s

https://janismac.github.io/ControlChallenges/?eyJjb2RlIjoiZnVuY3Rpb24gY29udHJvbEZ1bmN0aW9uKGJsb2NrKVxue1xuICB2YXIga3AgPSA1MDA7XG4gIHZhciBrZCA9IDU1O1xuICAvLyAwLjRcbiAgXG4gIGtwID0gNTAwO1xuICBrZCA9IDU1O1xuICBcbiAgcmV0dXJuIGtwKigwLWJsb2NrLngpLWtkKmJsb2NrLmR4O1xufVxuXG5cbiIsImx2bF9pZCI6IlR1dG9yaWFsQmxvY2tXaXRob3V0RnJpY3Rpb24ifQ==

**Comment by MSIhub** [comment]
Tutorial 1: 0.6s
https://janismac.github.io/ControlChallenges/?eyJjb2RlIjoiZnVuY3Rpb24gY29udHJvbEZ1bmN0aW9uKGJsb2NrKVxue1xuICB2YXIga3AgPSA1MDA7XG4gIHZhciBrZCA9IDUwO1xuICByZXR1cm4ga3AqKDAtYmxvY2sueCkgKyBrZCooMC1ibG9jay5keCk7XG59XG4iLCJsdmxfaWQiOiJUdXRvcmlhbEJsb2NrV2l0aEZyaWN0aW9uIn0=

**Comment by ArekBerc** [comment]
tutorial 1
http://janismac.github.io/ControlChallenges/?eyJjb2RlIjoidmFyIHRvdGFsPTAuMDtcbnZhciBwcmV2dGltZT0wLjA7XG52YXIgZHRpbWU9MC4wO1xuZnVuY3Rpb24gY29udHJvbEZ1bmN0aW9uKGJsb2NrKVxue1xuICBcbiAgZHRpbWUgPSBibG9jay5UIC0gcHJldnRpbWU7XG4gIHRvdGFsID0gdG90YWwgKyAoYmxvY2sueCAqIGR0aW1lKTtcbiAgcmV0dXJuIDUwKigwLWJsb2NrLngpIC0gKDEwKmJsb2NrLmR4KSAtICh0b3RhbCAqIDAuMDAwMDAwMDAwMDAwMDEpO1xuICBwcmV2dGltID0gYmxvY2suVDtcbn1cblxuXG5cblxuXG5cbiIsImx2bF9pZCI6IlR1dG9yaWFsQmxvY2tXaXRoRnJpY3Rpb24ifQ==

**Comment by MSIhub** [comment]
tutorial 2: 0.4 secs

https://janismac.github.io/ControlChallenges/?eyJjb2RlIjoiZnVuY3Rpb24gY29udHJvbEZ1bmN0aW9uKGJsb2NrKVxue1xuICAvL3JldHVybiA1Kk1hdGguc2luKDEwKmJsb2NrLlQpO1xuICB2YXIga3AgPSA1MDA7XG4gIHZhciBrZCA9IDYwO1xuICByZXR1cm4ga3AqKDAtYmxvY2sueCkgKyBrZCooMC1ibG9jay5keCk7XG59IiwibHZsX2lkIjoiVHV0b3JpYWxCbG9ja1dpdGhvdXRGcmljdGlvbiJ9

**Comment by Nesheit** [comment]
Tutorial 2:
https://janismac.github.io/ControlChallenges/?eyJjb2RlIjoiZnVuY3Rpb24gY29udHJvbEZ1bmN0aW9uKGJsb2NrKVxue1xuICByZXR1cm4gNTAwKigwIC0gYmxvY2sueCkgLSA2MCpibG9jay5keDtcbn0iLCJsdmxfaWQiOiJUdXRvcmlhbEJsb2NrV2l0aG91dEZyaWN0aW9uIn0=

0.4 sec.

**Comment by Nosilil** [comment]
T3 0.6s
http://janismac.github.io/ControlChallenges/?eyJjb2RlIjoiXG5mdW5jdGlvbiBjb250cm9sRnVuY3Rpb24oYmxvY2spXG57XG4gIHZhciBwID0gLTE0MDtcbiAgdmFyIGkgPSAwO1xuICB2YXIgZCA9IC0yMDtcbiAgXG4gIHJldHVybiBwICogKGJsb2NrLngrMC4wMSkgKyAgaSAqIGJsb2NrLlQgKiAoYmxvY2suZHgrMC4wMSkgKyBkICogKGJsb2NrLmR4KzAuMDEpIDtcbn1cblxuXG4iLCJsdmxfaWQiOiJUdXRvcmlhbEJsb2NrT25TbG9wZSJ9

**Comment by sigeek** [comment]
Tutorial 1: 0.44 s
https://janismac.github.io/ControlChallenges/?eyJjb2RlIjoiXG5mdW5jdGlvbiBjb250cm9sRnVuY3Rpb24oYmxvY2spXG57XG4gIHJldHVybiAtOTAwKmJsb2NrLnggLSA1MCpibG9jay54KmJsb2NrLlQgLSA5NSpibG9jay5keDtcbn1cblxuXG5cblxuXG4iLCJsdmxfaWQiOiJUdXRvcmlhbEJsb2NrV2l0aEZyaWN0aW9uIn0=

Tutorial 3: 0.82 s
https://janismac.github.io/ControlChallenges/?eyJjb2RlIjoiZnVuY3Rpb24gY29udHJvbEZ1bmN0aW9uKGJsb2NrKVxue1xuICByZXR1cm4gLTc1MCpibG9jay54IC01MDAqYmxvY2sueCpibG9jay5UIC0gODMqYmxvY2suZHg7XG59IiwibHZsX2lkIjoiVHV0b3JpYWxCbG9ja09uU2xvcGUifQ==

**Comment by MSIhub** [comment]
Tutorial 3: 0.72s
https://janismac.github.io/ControlChallenges/?eyJjb2RlIjoiZnVuY3Rpb24gY29udHJvbEZ1bmN0aW9uKGJsb2NrKVxue1xuICB2YXIga3AgPSA1MDA7XG4gIHZhciBrZCA9IDYwO1xuICBcbiAgcmV0dXJuIGtwKigwLWJsb2NrLngpICtrZCooMC1ibG9jay5keCk7XG59IiwibHZsX2lkIjoiVHV0b3JpYWxCbG9ja09uU2xvcGUifQ==

**Comment by khlee0697** [comment]
Tutorial 1 : 1.7 s

http://janismac.github.io/ControlChallenges/?eyJjb2RlIjoiXG5mdW5jdGlvbiBjb250cm9sRnVuY3Rpb24oYmxvY2spXG57XG4gIHJldHVybiAxNiooMCAtIGJsb2NrLngpIC0gNS43NSpibG9jay5keCArIDExKmJsb2NrLlQqKDAgLSBibG9jay54KSA7XG59XG5cbiIsImx2bF9pZCI6IlR1dG9yaWFsQmxvY2tXaXRoRnJpY3Rpb24ifQ==

Tutorial 2 : 2.14 s

http://janismac.github.io/ControlChallenges/?eyJjb2RlIjoiZnVuY3Rpb24gY29udHJvbEZ1bmN0aW9uKGJsb2NrKVxue1xuICAgcmV0dXJuIDEyKigwLjAxIC1ibG9jay54KSAtNi41KmJsb2NrLmR4ICsgNiooMC4wMSAtIGJsb2NrLngpKmJsb2NrLlQ7XG59XG5cblxuIiwibHZsX2lkIjoiVHV0b3JpYWxCbG9ja1dpdGhvdXRGcmljdGlvbiJ9

**Comment by lucarag** [comment]
http://janismac.github.io/ControlChallenges/?eyJjb2RlIjoiZnVuY3Rpb24gY29udHJvbEZ1bmN0aW9uKGJsb2NrKVxue1xuICByZXR1cm4gNTAwKigwIC0gYmxvY2sueCkgKyA1MCooMCAtIGJsb2NrLmR4KSAtIDAuMSpibG9jay5keDtcbn0iLCJsdmxfaWQiOiJUdXRvcmlhbEJsb2NrT25TbG9wZSJ9

**Comment by mett96** [comment]
Tutorial 3: 1s

https://janismac.github.io/ControlChallenges/?eyJjb2RlIjoidmFyIHRvdF9lPTA7XG52YXIgcHJldl9lPTA7XG5cbmZ1bmN0aW9uIGNvbnRyb2xGdW5jdGlvbihibG9jaylcbntcbiAgdmFyIGtwID0gNTAwO1xuICB2YXIga2QgPSAxMDA7XG4gIHZhciBraSA9IDEwO1xuICAvLyAzLjI0XG4gIFxuICB0b3RfZSArPSBibG9jay54O1xuICBcbiAga3AgPSAxMDAwO1xuICBrZCA9IDkwO1xuICBraSA9IDAuMTtcbiAgXG4gIHJldHVybiAta3AqYmxvY2sueCAtIGtpKmJsb2NrLmR4KmJsb2NrLlQgLSBrZCpibG9jay5keDtcbn0iLCJsdmxfaWQiOiJUdXRvcmlhbEJsb2NrT25TbG9wZSJ9

**Comment by abdelhakim96** [comment]
challenge 3: http://janismac.github.io/ControlChallenges/?eyJjb2RlIjoidmFyIHBvc2l0aW9uX2Vycm9yID0gMDtcbmZ1bmN0aW9uIGNvbnRyb2xGdW5jdGlvbihibG9jaylcbntcbiAgLy8gVXNpbmcgdGhlIFBEIENvbnRyb2xsZXIgZm9ybSB0dXRvcmlhbCAjMlxuICAvLyB0aGUgYmxvY2sgY29tZXMgdG8gcmVzdCwgYnV0IHRoZSBzbG9wZSBmb3JjZVxuICAvLyBwdWxscyBpdCBhd2F5IGZyb20gaXRzIHRhcmdldC5cbiAgLy8gSWRlYTogTWVhc3VyZSB0aGUgcG9zaXRpb24tZXJyb3Igb3ZlciB0aW1lLlxuICAvLyBUaGUgbG9uZ2VyIHRoZSBibG9jayBpcyBvbiB0aGUgcmlnaHQgb2YgdGhlXG4gIC8vIGFycm93LCB0aGUgaGFyZGVyIGl0IHNob3VsZCBiZSBwdWxsZWQgdG8gdGhlIGxlZnQuXG4gIC8vIFRoaXMgaXMga25vd24gYXMgYSBwcm9wb3J0aW9uYWwtaW50ZWdyYWwtZGVyaXZhdGl2ZSAob3IgUElEKSBjb250cm9sbGVyLlxuICBcbiAgcG9zaXRpb25fZXJyb3IgKz0gYmxvY2sueDsgIFxuICBtb25pdG9yKCdwb3NpdGlvbl9lcnJvcicscG9zaXRpb25fZXJyb3IpOyAgXG4gIHJldHVybiAgICAgLTU1MCpibG9jay54IC01MCpibG9jay5keC0xLjk1O1xufVxuXG4vLyByZXR1cm4gLTEwKmJsb2NrLnggLTUqYmxvY2suZHggLTAuMSpwb3NpdGlvbl9lcnJvci05LjgqTWF0aC5jb3MoMzApIiwibHZsX2lkIjoiVHV0b3JpYWxCbG9ja09uU2xvcGUifQ==

**Comment by Nesheit** [comment]
Tutorial 3:
https://janismac.github.io/ControlChallenges/?eyJjb2RlIjoiZnVuY3Rpb24gY29udHJvbEZ1bmN0aW9uKGJsb2NrKVxue1xuICByZXR1cm4gOTAwKigwIC0gYmxvY2sueCkgKyA0NSooMCAtIGJsb2NrLngpL2Jsb2NrLlQgLSA5MCpibG9jay5keDtcbn0iLCJsdmxfaWQiOiJUdXRvcmlhbEJsb2NrT25TbG9wZSJ9
1.06 sec

**Comment by wenxuanmou** [comment]
Tutorial 3.
function controlFunction(block)
{
  return 30*(0-block.x)+10*(0-block.dx)+150*(0-block.x*block.T);
}
1.3 seconds

**Comment by MartinaRuocco** [comment]
Not the best values for sure but it just needs better Ks:

[Tutorial 1 ](http://janismac.github.io/ControlChallenges/?eyJjb2RlIjoiZnVuY3Rpb24gY29udHJvbEZ1bmN0aW9uKGJsb2NrKVxue1xuICByZXR1cm4gMyooMCAtIGJsb2NrLngpICsgMiooMCAtIGJsb2NrLmR4KTtcbn0iLCJsdmxfaWQiOiJUdXRvcmlhbEJsb2NrV2l0aEZyaWN0aW9uIn0=) = 3.34s

[Tutorial 2](http://janismac.github.io/ControlChallenges/?eyJjb2RlIjoiZnVuY3Rpb24gY29udHJvbEZ1bmN0aW9uKGJsb2NrKVxue1xuICByZXR1cm4gLTMqYmxvY2sueCAtIDMqYmxvY2suZHg7XG59IiwibHZsX2lkIjoiVHV0b3JpYWxCbG9ja1dpdGhvdXRGcmljdGlvbiJ9) = 3.36s

[Tutorial 3](
http://janismac.github.io/ControlChallenges/?eyJjb2RlIjoidmFyIHN1bV9lID0gMDtcbmZ1bmN0aW9uIGNvbnRyb2xGdW5jdGlvbihibG9jaylcbntcbiAgc3VtX2UgKz0gYmxvY2sueDtcbiAgbW9uaXRvcigncG9zaXRpb25fZXJyb3InLHN1bV9lKTtcbiAgcmV0dXJuIC0xMDAqYmxvY2sueCAtMzAqYmxvY2suZHggLTEwKnN1bV9lKmJsb2NrLlQ7XG59IiwibHZsX2lkIjoiVHV0b3JpYWxCbG9ja09uU2xvcGUifQ==) = 5.68s
