### ISSUE TITLE
Assignment on Git

### ISSUE THREAD

**Issue by pattacini** [easy-peasy-robotics/easy-peasy-robotics.github.io#4]
Hello @easy-peasy-robotics/cpi17-campuseros 

Now that you're in the team, what about warming up in sight of the crash course?
Then, let's go through the very basics of `git` by taking this simple assignment 📝 👨‍🎓 

- Click on the link https://classroom.github.com/a/TdwXeyIF and accept the assignment
- You'll be given a private repository along with a guide on how to complete the assignment using the so-called **smoke test**.

Enjoy!

---

Did you receive this notification from GitHub, right? 😉 
In case not, check out instructions on [**how to trim** GitHub notifications](https://github.com/easy-peasy-robotics/easy-peasy-robotics.github.io/wiki/Before-arriving-at-Campus-Party#aob) 🔔

**Comment by pattacini** [comment]
Congrats @xEnVrE 🎉 

You've been the first to score *1* point.
Test passed 🎖 

😉

**Comment by xEnVrE** [comment]
Thank you @pattacini :smile:

**Comment by pattacini** [comment]
@succoDiPompelmo got the point too!
