### ISSUE TITLE
Assignment on Yarp 

### ISSUE THREAD

**Issue by giuliavezzani** [easy-peasy-robotics/easy-peasy-robotics.github.io#5]
Hello @easy-peasy-robotics/cpi17-campuseros,

let's start with the **first assignment** :memo: of this crash course! :muscle: 

- Click on the link: https://classroom.github.com/a/AxLu1A1H and accept the assignment
- You'll be given a private repository along with a guide on how to complete the assignment using the so-called **smoke test**.

**Comment by pattacini** [comment]
You'll be challenged with this assignment in a while. There's a tutorial first.
@easy-peasy-robotics/cpi17-campuseros don't go too fast 😉
